#!/bin/bash

# Header of the table with a nice format
echo -e "\n\033[1mDomain Information Report\033[0m"
echo "---------------------------------------------------------------"
printf "%-40s %-15s %-80s %-25s\n" "Domain" "Type" "Documentroot" "Userdirprotect"
echo "---------------------------------------------------------------"

# Command to get the data
output=$(uapi DomainInfo domains_data)

# Initialize variables to hold the values
domain_list=""
type_list=""
documentroot_list=""
userdirprotect_list=""

# Loop through the output and extract relevant fields for each domain
while read -r line; do
    domain=$(echo "$line" | grep -i "domain" | awk '{print $2}')
    type=$(echo "$line" | grep -i "type" | awk '{print $2}')
    documentroot=$(echo "$line" | grep -i "documentroot" | awk '{print substr($0, index($0,$2))}')
    userdirprotect=$(echo "$line" | grep -i "userdirprotect" | awk '{print $2}')
    
    # Concatenate each domain's info to the respective variables
    if [ -n "$domain" ] && [ -n "$type" ]; then
        domain_list+="$domain "
        type_list+="$type "
        documentroot_list+="$documentroot "
        userdirprotect_list+="$userdirprotect "
    fi
done <<< "$output"

# Now, let's print the data nicely aligned
count=$(echo "$domain_list" | wc -w)
for i in $(seq 1 $count); do
  domain=$(echo "$domain_list" | cut -d' ' -f$i)
  type=$(echo "$type_list" | cut -d' ' -f$i)
  documentroot=$(echo "$documentroot_list" | cut -d' ' -f$i)
  userdirprotect=$(echo "$userdirprotect_list" | cut -d' ' -f$i)
  
  # Print each record formatted
  printf "%-40s %-15s %-80s %-25s\n" "$domain" "$type" "$documentroot" "$userdirprotect"
done

echo "---------------------------------------------------------------"
