#!/bin/bash

# Define Colors
red="\e[31m█\e[0m"      # Red Shade
white="\e[37m█\e[0m"    # White Shade
blue="\e[34m█\e[0m"     # Blue Shade
green="\e[32m█\e[0m"    # Green Shade
shadow="\e[90m█\e[0m"   # Shadow Effect for 3D Look
space=" "               # Space for alignment

# Clear the screen
clear

# Printing a 3D Spherical Design
echo -e "\n\n"
echo -e "               $shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow"
echo -e "           $shadow$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$shadow"
echo -e "        $shadow$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$shadow"
echo -e "      $shadow$red$red$red$white$white$white$white$white$white$white$white$white$white$red$red$red$shadow"
echo -e "     $shadow$red$red$white$white$white$blue$blue$blue$blue$blue$blue$blue$white$white$white$red$red$shadow"
echo -e "     $shadow$red$red$white$white$blue$blue$blue$blue$blue$blue$blue$blue$white$white$red$red$shadow"
echo -e "     $shadow$red$red$white$white$white$blue$blue$blue$blue$blue$blue$blue$white$white$white$red$red$shadow"
echo -e "      $shadow$red$red$red$white$white$white$white$white$white$white$white$white$white$red$red$red$shadow"
echo -e "        $shadow$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$shadow"
echo -e "           $shadow$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$red$shadow"
echo -e "               $shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow$shadow"
echo -e "\n"

# Beautiful 3D Text
echo -e "\e[1;36m            ✨ ELEVATE YOUR SPIRIT ✨\e[0m"
echo -e "\e[1;33m        🌍 UNITY IN DIVERSITY 🌍\e[0m"
echo -e "\n"
