#!/bin/bash

# Define colors
orange="\e[48;5;202m  \e[0m"  # Saffron (Top)
white="\e[48;5;15m  \e[0m"    # White (Middle)
green="\e[48;5;28m  \e[0m"    # Green (Bottom)
blue="\e[34m●\e[0m"          # Ashoka Chakra (Center)

# Clear the screen
clear

# Print the Indian Flag with enhanced design
echo -e "\n"
for i in {1..5}; do
  echo -e "   $orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange"
done
for i in {1..3}; do
  echo -e "   $white$white$white$white$white$white$white$white$blue$white$white$white$white$white$white$white$white$white$white"
done
for i in {1..5}; do
  echo -e "   $green$green$green$green$green$green$green$green$green$green$green$green$green$green$green$green$green$green$green"
done

# Print the Ashoka Chakra Design
echo -e "\n        \e[34m⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫ ⚫\e[0m\n"

# Finish with a Bold Message
echo -e "\n\e[1;33m         🇮🇳  JAI HIND! 🇮🇳\e[0m\n"
