#!/bin/bash

# Colors
orange="\e[48;5;208m  \e[0m"
white="\e[48;5;15m  \e[0m"
green="\e[48;5;28m  \e[0m"
blue="\e[34m●\e[0m"

# Clear screen
clear

# Print the Indian Flag
echo -e "\n"
for i in {1..4}; do
  echo -e "  $orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange$orange"
done
for i in {1..2}; do
  echo -e "  $white$white$white$white$white$white$white$white$blue$white$white$white$white$white$white$white$white"
done
for i in {1..4}; do
  echo -e "  $green$green$green$green$green$green$green$green$green$green$green$green$green$green$green$green"
done

# Print Ashoka Chakra lines
echo -e "\n        \e[34m- - - - - - - - - - -\e[0m\n"

# Finish
echo -e "\n\e[1;33m    🇮🇳 JAI HIND! 🇮🇳\e[0m\n"
